/*
Author     : Shreya Appia
Description: SQL commands to create Ownews database schema and required tables
*/

CREATE SCHEMA Ownews;

CREATE TABLE LOGIN_DETAILS (
   USERNAME VARCHAR(20) NOT NULL,
   PASSWORD VARCHAR(32) NOT NULL,
   USERID MEDIUMINT NOT NULL AUTO_INCREMENT,
   EMAILID VARCHAR(255) NOT NULL,
   ENABLED tinyint(1) NOT NULL,
   PRIMARY KEY(USERID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AUTHORITIES (
  USERID MEDIUMINT NOT NULL AUTO_INCREMENT,
  AUTHORITY VARCHAR(45) NOT NULL,
  PRIMARY KEY (USERID),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USERID) REFERENCES LOGIN_DETAILS (USERID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE NEWS (
	NEWSID MEDIUMINT NOT NULL AUTO_INCREMENT,
	USERID MEDIUMINT NOT NULL,
	NEWS_LINK VARCHAR(255) NOT NULL,
	POSTED_TIME TIMESTAMP NOT NULL,
	VOTES MEDIUMINT NOT NULL,
	POPULARITY DOUBLE NOT NULL,
	PRIMARY KEY (NEWSID),
	CONSTRAINT FK_USER_ID_1 FOREIGN KEY (USERID) REFERENCES LOGIN_DETAILS (USERID) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RELATIONSHIP (
	RELATIONID MEDIUMINT NOT NULL AUTO_INCREMENT,
	USERID MEDIUMINT NOT NULL,
	FRIENDID MEDIUMINT NOT NULL,
	RELATION DOUBLE NOT NULL,
	RELATION_VOTES MEDIUMINT NOT NULL,
	RELATION_FLAG MEDIUMINT NOT NULL,
	PRIMARY KEY (RELATIONID),
	CONSTRAINT FK_USER_ID_2 FOREIGN KEY (USERID) REFERENCES LOGIN_DETAILS (USERID) ON DELETE CASCADE,
	CONSTRAINT FK_USER_ID_3 FOREIGN KEY (FRIENDID) REFERENCES LOGIN_DETAILS (USERID) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE VOTED_POSTS (
	POSTID MEDIUMINT NOT NULL AUTO_INCREMENT,
	USERID MEDIUMINT NOT NULL,
	NEWSID MEDIUMINT NOT NULL,
	VOTED_TIME TIMESTAMP NOT NULL,
	RATING MEDIUMINT NOT NULL,
	PRIMARY KEY (POSTID),
	CONSTRAINT FK_USER_ID_4 FOREIGN KEY (USERID) REFERENCES LOGIN_DETAILS (USERID) ON DELETE CASCADE,
	CONSTRAINT FK_NEWS_ID FOREIGN KEY (NEWSID) REFERENCES NEWS (NEWSID) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
